// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: proto/watchlist/watchlist.proto

package watchlist

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// List Wachlist by page
type ListWatchlistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page     int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListWatchlistRequest) Reset() {
	*x = ListWatchlistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_watchlist_watchlist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWatchlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchlistRequest) ProtoMessage() {}

func (x *ListWatchlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchlist_watchlist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchlistRequest.ProtoReflect.Descriptor instead.
func (*ListWatchlistRequest) Descriptor() ([]byte, []int) {
	return file_proto_watchlist_watchlist_proto_rawDescGZIP(), []int{0}
}

func (x *ListWatchlistRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListWatchlistRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWatchlistRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListWatchlistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalCount int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListWatchlistResponse) Reset() {
	*x = ListWatchlistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_watchlist_watchlist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWatchlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchlistResponse) ProtoMessage() {}

func (x *ListWatchlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchlist_watchlist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchlistResponse.ProtoReflect.Descriptor instead.
func (*ListWatchlistResponse) Descriptor() ([]byte, []int) {
	return file_proto_watchlist_watchlist_proto_rawDescGZIP(), []int{1}
}

func (x *ListWatchlistResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListWatchlistResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// AddMovie to Watchlist
type AddMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId int32 `protobuf:"varint,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
}

func (x *AddMovieRequest) Reset() {
	*x = AddMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_watchlist_watchlist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMovieRequest) ProtoMessage() {}

func (x *AddMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchlist_watchlist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMovieRequest.ProtoReflect.Descriptor instead.
func (*AddMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_watchlist_watchlist_proto_rawDescGZIP(), []int{2}
}

func (x *AddMovieRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddMovieRequest) GetMovieId() int32 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type AddMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId int32 `protobuf:"varint,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
}

func (x *AddMovieResponse) Reset() {
	*x = AddMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_watchlist_watchlist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMovieResponse) ProtoMessage() {}

func (x *AddMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchlist_watchlist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMovieResponse.ProtoReflect.Descriptor instead.
func (*AddMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_watchlist_watchlist_proto_rawDescGZIP(), []int{3}
}

func (x *AddMovieResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddMovieResponse) GetMovieId() int32 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

// AddMovie to Watchlist
type RemoveMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId int32 `protobuf:"varint,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
}

func (x *RemoveMovieRequest) Reset() {
	*x = RemoveMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_watchlist_watchlist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMovieRequest) ProtoMessage() {}

func (x *RemoveMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchlist_watchlist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMovieRequest.ProtoReflect.Descriptor instead.
func (*RemoveMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_watchlist_watchlist_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveMovieRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveMovieRequest) GetMovieId() int32 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type RemoveMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *RemoveMovieResponse) Reset() {
	*x = RemoveMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_watchlist_watchlist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMovieResponse) ProtoMessage() {}

func (x *RemoveMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_watchlist_watchlist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMovieResponse.ProtoReflect.Descriptor instead.
func (*RemoveMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_watchlist_watchlist_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveMovieResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_proto_watchlist_watchlist_proto protoreflect.FileDescriptor

var file_proto_watchlist_watchlist_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73,
	0x74, 0x2f, 0x77, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x77, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x60, 0x0a, 0x14,
	0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x51,
	0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x45, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64,
	0x22, 0x48, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x13, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0xf2, 0x01, 0x0a, 0x09, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x52, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x77, 0x61, 0x74, 0x63,
	0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x77, 0x61, 0x74,
	0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x08,
	0x41, 0x64, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x1a, 0x2e, 0x77, 0x61, 0x74, 0x63, 0x68,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x77, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x41, 0x64, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x12, 0x1d, 0x2e, 0x77, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x77, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x14, 0x5a, 0x12, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x74, 0x63,
	0x68, 0x6c, 0x69, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_watchlist_watchlist_proto_rawDescOnce sync.Once
	file_proto_watchlist_watchlist_proto_rawDescData = file_proto_watchlist_watchlist_proto_rawDesc
)

func file_proto_watchlist_watchlist_proto_rawDescGZIP() []byte {
	file_proto_watchlist_watchlist_proto_rawDescOnce.Do(func() {
		file_proto_watchlist_watchlist_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_watchlist_watchlist_proto_rawDescData)
	})
	return file_proto_watchlist_watchlist_proto_rawDescData
}

var file_proto_watchlist_watchlist_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_watchlist_watchlist_proto_goTypes = []any{
	(*ListWatchlistRequest)(nil),  // 0: watchlist.ListWatchlistRequest
	(*ListWatchlistResponse)(nil), // 1: watchlist.ListWatchlistResponse
	(*AddMovieRequest)(nil),       // 2: watchlist.AddMovieRequest
	(*AddMovieResponse)(nil),      // 3: watchlist.AddMovieResponse
	(*RemoveMovieRequest)(nil),    // 4: watchlist.RemoveMovieRequest
	(*RemoveMovieResponse)(nil),   // 5: watchlist.RemoveMovieResponse
}
var file_proto_watchlist_watchlist_proto_depIdxs = []int32{
	0, // 0: watchlist.Watchlist.ListWatchlist:input_type -> watchlist.ListWatchlistRequest
	2, // 1: watchlist.Watchlist.AddMovie:input_type -> watchlist.AddMovieRequest
	4, // 2: watchlist.Watchlist.RemoveMovie:input_type -> watchlist.RemoveMovieRequest
	1, // 3: watchlist.Watchlist.ListWatchlist:output_type -> watchlist.ListWatchlistResponse
	3, // 4: watchlist.Watchlist.AddMovie:output_type -> watchlist.AddMovieResponse
	5, // 5: watchlist.Watchlist.RemoveMovie:output_type -> watchlist.RemoveMovieResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_watchlist_watchlist_proto_init() }
func file_proto_watchlist_watchlist_proto_init() {
	if File_proto_watchlist_watchlist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_watchlist_watchlist_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListWatchlistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_watchlist_watchlist_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListWatchlistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_watchlist_watchlist_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AddMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_watchlist_watchlist_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AddMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_watchlist_watchlist_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_watchlist_watchlist_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_watchlist_watchlist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_watchlist_watchlist_proto_goTypes,
		DependencyIndexes: file_proto_watchlist_watchlist_proto_depIdxs,
		MessageInfos:      file_proto_watchlist_watchlist_proto_msgTypes,
	}.Build()
	File_proto_watchlist_watchlist_proto = out.File
	file_proto_watchlist_watchlist_proto_rawDesc = nil
	file_proto_watchlist_watchlist_proto_goTypes = nil
	file_proto_watchlist_watchlist_proto_depIdxs = nil
}
