// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: watchlist/watchlist.proto

package watchlist

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// List Wachlist by page
type ListWatchlistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListWatchlistRequest) Reset() {
	*x = ListWatchlistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watchlist_watchlist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWatchlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchlistRequest) ProtoMessage() {}

func (x *ListWatchlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watchlist_watchlist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchlistRequest.ProtoReflect.Descriptor instead.
func (*ListWatchlistRequest) Descriptor() ([]byte, []int) {
	return file_watchlist_watchlist_proto_rawDescGZIP(), []int{0}
}

func (x *ListWatchlistRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListWatchlistRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListWatchlistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalCount int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListWatchlistResponse) Reset() {
	*x = ListWatchlistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watchlist_watchlist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWatchlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchlistResponse) ProtoMessage() {}

func (x *ListWatchlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watchlist_watchlist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchlistResponse.ProtoReflect.Descriptor instead.
func (*ListWatchlistResponse) Descriptor() ([]byte, []int) {
	return file_watchlist_watchlist_proto_rawDescGZIP(), []int{1}
}

func (x *ListWatchlistResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListWatchlistResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// AddMovie to Watchlist
type AddToWatchlistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId int32 `protobuf:"varint,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
}

func (x *AddToWatchlistRequest) Reset() {
	*x = AddToWatchlistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watchlist_watchlist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToWatchlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToWatchlistRequest) ProtoMessage() {}

func (x *AddToWatchlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watchlist_watchlist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToWatchlistRequest.ProtoReflect.Descriptor instead.
func (*AddToWatchlistRequest) Descriptor() ([]byte, []int) {
	return file_watchlist_watchlist_proto_rawDescGZIP(), []int{2}
}

func (x *AddToWatchlistRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddToWatchlistRequest) GetMovieId() int32 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type AddToWatchlistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId int32 `protobuf:"varint,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
}

func (x *AddToWatchlistResponse) Reset() {
	*x = AddToWatchlistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watchlist_watchlist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToWatchlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToWatchlistResponse) ProtoMessage() {}

func (x *AddToWatchlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watchlist_watchlist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToWatchlistResponse.ProtoReflect.Descriptor instead.
func (*AddToWatchlistResponse) Descriptor() ([]byte, []int) {
	return file_watchlist_watchlist_proto_rawDescGZIP(), []int{3}
}

func (x *AddToWatchlistResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddToWatchlistResponse) GetMovieId() int32 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

// AddMovie to Watchlist
type RemoveFromWatchlistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId int32 `protobuf:"varint,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
}

func (x *RemoveFromWatchlistRequest) Reset() {
	*x = RemoveFromWatchlistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watchlist_watchlist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromWatchlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromWatchlistRequest) ProtoMessage() {}

func (x *RemoveFromWatchlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watchlist_watchlist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromWatchlistRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromWatchlistRequest) Descriptor() ([]byte, []int) {
	return file_watchlist_watchlist_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveFromWatchlistRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveFromWatchlistRequest) GetMovieId() int32 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type RemoveFromWatchlistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId int32 `protobuf:"varint,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
}

func (x *RemoveFromWatchlistResponse) Reset() {
	*x = RemoveFromWatchlistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watchlist_watchlist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFromWatchlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromWatchlistResponse) ProtoMessage() {}

func (x *RemoveFromWatchlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watchlist_watchlist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromWatchlistResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromWatchlistResponse) Descriptor() ([]byte, []int) {
	return file_watchlist_watchlist_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveFromWatchlistResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveFromWatchlistResponse) GetMovieId() int32 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

var File_watchlist_watchlist_proto protoreflect.FileDescriptor

var file_watchlist_watchlist_proto_rawDesc = []byte{
	0x0a, 0x19, 0x77, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x77, 0x61, 0x74, 0x63,
	0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x77, 0x61, 0x74,
	0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x22, 0x51, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4b, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x54, 0x6f,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x49, 0x64, 0x22, 0x50, 0x0a, 0x1a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x1b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x57, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x32, 0x9c, 0x02, 0x0a, 0x09, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x52, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x77, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x77, 0x61, 0x74, 0x63, 0x68, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x41, 0x64, 0x64,
	0x54, 0x6f, 0x57, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x77, 0x61,
	0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x77, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x64, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x2e, 0x77, 0x61, 0x74, 0x63, 0x68, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26,
	0x2e, 0x77, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x57, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x77, 0x61, 0x74, 0x63, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_watchlist_watchlist_proto_rawDescOnce sync.Once
	file_watchlist_watchlist_proto_rawDescData = file_watchlist_watchlist_proto_rawDesc
)

func file_watchlist_watchlist_proto_rawDescGZIP() []byte {
	file_watchlist_watchlist_proto_rawDescOnce.Do(func() {
		file_watchlist_watchlist_proto_rawDescData = protoimpl.X.CompressGZIP(file_watchlist_watchlist_proto_rawDescData)
	})
	return file_watchlist_watchlist_proto_rawDescData
}

var file_watchlist_watchlist_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_watchlist_watchlist_proto_goTypes = []any{
	(*ListWatchlistRequest)(nil),        // 0: watchlist.ListWatchlistRequest
	(*ListWatchlistResponse)(nil),       // 1: watchlist.ListWatchlistResponse
	(*AddToWatchlistRequest)(nil),       // 2: watchlist.AddToWatchlistRequest
	(*AddToWatchlistResponse)(nil),      // 3: watchlist.AddToWatchlistResponse
	(*RemoveFromWatchlistRequest)(nil),  // 4: watchlist.RemoveFromWatchlistRequest
	(*RemoveFromWatchlistResponse)(nil), // 5: watchlist.RemoveFromWatchlistResponse
}
var file_watchlist_watchlist_proto_depIdxs = []int32{
	0, // 0: watchlist.Watchlist.ListWatchlist:input_type -> watchlist.ListWatchlistRequest
	2, // 1: watchlist.Watchlist.AddToWatchlist:input_type -> watchlist.AddToWatchlistRequest
	4, // 2: watchlist.Watchlist.RemoveFromWatchlist:input_type -> watchlist.RemoveFromWatchlistRequest
	1, // 3: watchlist.Watchlist.ListWatchlist:output_type -> watchlist.ListWatchlistResponse
	3, // 4: watchlist.Watchlist.AddToWatchlist:output_type -> watchlist.AddToWatchlistResponse
	5, // 5: watchlist.Watchlist.RemoveFromWatchlist:output_type -> watchlist.RemoveFromWatchlistResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_watchlist_watchlist_proto_init() }
func file_watchlist_watchlist_proto_init() {
	if File_watchlist_watchlist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_watchlist_watchlist_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListWatchlistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watchlist_watchlist_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListWatchlistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watchlist_watchlist_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AddToWatchlistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watchlist_watchlist_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AddToWatchlistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watchlist_watchlist_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveFromWatchlistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watchlist_watchlist_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveFromWatchlistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_watchlist_watchlist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_watchlist_watchlist_proto_goTypes,
		DependencyIndexes: file_watchlist_watchlist_proto_depIdxs,
		MessageInfos:      file_watchlist_watchlist_proto_msgTypes,
	}.Build()
	File_watchlist_watchlist_proto = out.File
	file_watchlist_watchlist_proto_rawDesc = nil
	file_watchlist_watchlist_proto_goTypes = nil
	file_watchlist_watchlist_proto_depIdxs = nil
}
